### ISSUE TITLE
code assist problem with AlloyUI

### ISSUE THREAD

**Issue by lilu1990** [angelozerr/tern-aui2.0.x#15]
for project has only AlloyUI module selected (with no yui3.0) if I do code assist in the situation like 
AUI().use('aui-base',function(A){
new A. +(code assist)
})
![aui only](https://cloud.githubusercontent.com/assets/4350803/5896808/b103d208-a576-11e4-9889-c47170fe96c4.PNG)
it will get no proposal

but in the situation 
AUI().use('aui-base',function(A){
new A.ad+(code assist)
}) 
it can get the suggestions like "add:fn -aui1.5x" and "add(data,field,amount):Date -aui1.5x"

**Comment by angelozerr** [comment]
AlloyUI tern plugin works only with YUI3. So you need select YUI3.

The result of add in the compeltion is because tern tries to find some result when it foun dnothing. By default this option is setted. I will provide a preferences to disable that. See https://github.com/angelozerr/tern.java/issues/235

**Comment by lilu1990** [comment]
Thanks angelozerr , closing
